InteractableDialog Bugfixes
GTcreyon/SM63Redux pull request #120
Opened 2023-03-27 13:33 UTC by Kuma-Boo

# Description of changes

- Bugfixes
- Moves sign/toad's state check to the InteractableDialog class for more consistency in dialog activation

# Issue(s)

Closes #115 
Closes #59 
Closes #105

2023-03-27 15:41 UTC, Koopa1018 requested changes
Not certain about mixing multiple systems' changes like this (pound and Interactable fixes), but there's no denying they're solid fixes. We can probably get these merged pretty soon.

(Might want to look at the style guide in the meantime. `CONTRIBUTING.md`, at the root of the repo.)

2023-03-30 02:36 UTC, Koopa1018 requested changes
Nice work. Before we merge, would you mind making some style changes to function spacing and comment formatting? (Functions should have two lines between, and comments should have a space after the `#`.)

2023-03-31 01:49 UTC, Koopa1018 reviewed
Good stuff, good stuff. Keep going, is all I'd say. Also, check the PR's "Files changed" tab. Should help you find unformatted spots.

2023-03-31 01:49 UTC, Koopa1018 commented on classes/interactable/sign/sign.gd
> -func _state_check(body) -> bool:
Tricky to see, but a line's been deleted here too

2023-03-31 02:40 UTC, Kuma-Boo commented
Good grief, all these formatting mistakes are going to be the end of me 🤣

2023-03-31 12:44 UTC, Koopa1018 approved these changes
Looks good.

2023-03-31 12:45 UTC, merged