Upgrade ResidualSFX.new_from_existing error handling
GTcreyon/SM63Redux pull request #133
Opened 2023-04-02 01:01 UTC by Koopa1018

# Description of changes
Upgrades `ResidualSFX.new_from_existing` to handle more errors, better.

In particular, it now does the following:

- Crashes if the node it was given is not an audio source. (This can be downgraded to an error if needed.)
- Prints an error if the node it was given is an `AudioStreamPlayer3D`. Since the game is 2D, these probably shouldn't be in use anyway.
- Prints an error if the destroy-on-finished-playing signal is connected twice. This situation already errors, but handling it manually lets us give more specific information: what exactly is going wrong, what's been known to cause this before, where to check to try and fix it.

# Issue(s)
Was supposed to deal with #130. It didn't, but it should still be helpful in fixing that bug.

2023-04-09 14:11 UTC, GTcreyon requested changes
Overall good, but I think demoting to an error rather than a crash seems best.

2023-04-09 14:11 UTC, GTcreyon commented on classes/misc/residual_sfx/residual_sfx.gd
> +	assert(
A crash seems excessive. An error should be fine, no? We're not handling saved data, nor would anything particularly serious occur should this be incorrect.

2023-04-09 14:11 UTC, GTcreyon commented on classes/misc/residual_sfx/residual_sfx.gd
> +			or sfx is AudioStreamPlayer3D, # just for completeness
Please capitalize comments.

2023-04-11 01:58 UTC, Koopa1018 commented
Arright, fixed.

2023-04-19 21:24 UTC, GTcreyon approved these changes

2023-04-19 21:24 UTC, merged