Add underwater spin sound
GTcreyon/SM63Redux pull request #70
Opened 2023-02-21 07:54 UTC by Koopa1018

# Description of changes
Adds an underwater variant of the spin sound.

Implementation is based on #69 (obligatory number joke here). The spin sound is now routed through "SFX Clear In Water," which bypasses the underwater low-pass filter for a much clearer sound. The sound is designed with this in mind, and should blend with other underwater sounds perfectly fine.
# Reviewer(s)

@GTcreyon 
@Charpurrr 
@brickblock369 

# Issue(s)
Checks one box on #35.

2023-02-22 15:59 UTC, GTcreyon requested changes
Running the game causes the console to be flooded with the following error:
```
E 0:00:00.935   set_bus_mute: Index p_bus = -1 is out of bounds (buses.size() = 7).
  <C++ Source>  servers/audio_server.cpp:764 @ set_bus_mute()
  <Stack Trace> options_menu.gd:53 @ _process()
```

It seems that default_bus_layout.tres is misconfigured. Could you take a look at that?

2023-02-22 15:59 UTC, GTcreyon commented on default_bus_layout.tres
> +bus/2/name = "~~Water Muffle:"
Why are there two buses named `~~Water Muffle:`?

2023-02-22 15:59 UTC, GTcreyon commented on default_bus_layout.tres
> +bus/6/name = "~~SFX Clear In Water~~"
Equally, why are there 2 buses named `~~SFX Clear In Water~~`?

And there is no bus named `~Water Verb:` for bus 6 to send to.

2023-02-22 15:59 UTC, GTcreyon commented on classes/player/player.tscn
> +bus = "~~SFX Clear In Water~~"
This should be "~Water Verb:" I think?

2023-02-23 04:56 UTC, Koopa1018 commented
Ahhh frick, that looks like a failed merge :/
(I didn't think to separate this and #69 until after I'd already made them together in one branch. It seems I failed to separate them properly.)

2023-02-23 05:07 UTC, Koopa1018 commented
Alright, should be fixed.

2023-02-27 21:13 UTC, Koopa1018 commented
Easier said than done, due to the way the sound is authored (I'd have to implement the fade in code, then make sure it only happens if the user's not still holding the button).

If it's a cleaner ending you want, it'd be way easier to just play a short secondary sound when the user stops spinning.

2023-02-28 13:50 UTC, GTcreyon commented
> If it's a cleaner ending you want, it'd be way easier to just play a short secondary sound when the user stops spinning.

That seems reasonable.

2023-03-03 08:12 UTC, Koopa1018 commented
Arright, should sound better now.

2023-03-04 12:46 UTC, GTcreyon approved these changes
Minor issue where the sound continues playing if you exit water while spinning, but it's not too significant. This is easiest to pull off by power swimming in t1r2.

2023-03-04 12:46 UTC, merged